# from node:alpine
FROM node:6.9.4

# ch workdir to /app
WORKDIR '/app'

# copy file into
COPY package.json .
RUN npm install

# copy rest of the files
COPY . .

EXPOSE 3000

# run it
CMD ["npm", "run", "start"]

##
